export const TOKEN_CONTRACT_ADDRESS = "ADDRESS_OF_TOKEN_CONTRACT";
export const FACTORY_CONTRACT_ADDRESS = "ADDRESS_OF_FACTORY_CONTRACT";
export const TOKEN_CONTRACT_ABI = ABI_OF_TOKEN_CONTRACT;
export const FACTORY_CONTRACT_ABI = ABI_OF_FACTORY_CONTRACT;
export const EXCHANGE_CONTRACT_ABI = ABI_OF_EXCHANGE_CONTRACT;
